config/routes.rb
Rails.application.routes.draw do

  resources :photos
  namespace :admin do
    resources :users
    resources :albums
    resources :artists
    resources :musicians
    resources :songs

    root to: "users#index"
  end

  resources :api, :only => :index

  resources :songs

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/index'
  delete 'users/sign_out'

  resources :artists
  resources :albums
  resources :search
  resources :musicians

  root 'home#index'

  resources :user

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :albums
	has_many :musicians

	accepts_nested_attributes_for :musicians

	include PgSearch
	multisearchable :against => :name

end

app/controllers/admin/artists_controller.rb
module Admin
  class ArtistsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Artist.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Artist.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def index
		@artists = Artist.all
	end

	def show
		@artist = Artist.find(params[:id])
		@albums = Album.where(:artist_id => @artist.id)

		@array_of_cities = Album.list_of_locations
		@hash_of_city_albums_count = Album.count_of_albums_per_city

		@genres = Album.album_count(Album.uniq.pluck(:genre))
		@format = Album.album_count(Album.uniq.pluck(:format))

	end

	private

end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>Url</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.city %></td>
        <td><%= artist.url %></td>
        <td><%= artist.bio %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="bodyContainer">

        <div class="rowWrapper flex margin-top margin-left margin-right-big">
            <div class="searchBox search flex">
                    <form action="">
                        <input method="" name="" type="text" placeholder="Search for an album, artist or track..." class="search__input padding-10" id="search" required><span class="icons icons--search color-light-grey"></span>
                    </form>
            </div>

            <div class="sort flex">
                <div class="sortText color-light-grey">
                    SORT
                </div>

                <div class="sortBy">
                         <select>
                            <option>UPLOAD DATE, NEW TO OLD</option>
                            <option>Option 2</option>
                            <option>Option 3</option>
                        </select>

                        <div class="arrows">
                            <i class="arr-up"></i>
                            <i class="arr-down"></i>
                        </div>
                </div>
            </div>

            <div class="view flex">
                <div class="viewBig">
                <!-- Currently placeholder text that needs to be replaced with a text icon. Make sure to edit font size and width in style-layout.css for view class. -->
                    XXX
                </div>

                <div class="viewSmall">
                <!-- Currently placeholder text that needs to be replaced with a text icon. Make sure to edit font size and width in style-layout.css for view class. -->
                    XXX
                </div>
            </div>
        </div>


        <div class="contentContainer flex">
            <div class="leftContainer flex margin-top margin-left margin-btm">

                <div class="pageTitle">
                    <div class="pageTitle__text color-white flex space-between">
                        <div>
                            <%= @artist.name %> 
                            <span class="filterType"> | Artist</span>
                        </div>
                            <span><%= link_to 'EDIT ARTIST', edit_admin_artist_path(@artist), :class => "editLink" %></span>
                    </div>
                </div>

                <div class="artistImgContainer">
                    <img src="img/BrightEyes.jpg" class="artistImg" alt="Bright Eyes">
                    <!-- Need to populate image from database -->
                </div>
                
                <div class="line margin-top">
                </div>

                <div class="artistInfoWrapper flex">
                    <div class="artistInfoTitle">
                        BIO
                    </div>
                    <div class="artistInfoTitle">
                        MEMBERS
                    </div>
                </div>

                <div class="line">
                </div>

                <div class="artistInfoWrapper flex margin-top">
                    <div class="artistBio font-oswald-light color-darkest-grey">        
                    <%= @artist.bio %>
                    </div>

                    <div class="artistMembers font-oswald-light color-darkest-grey">
                    <!-- member__name and member__instrument should be dynamically populated from form data -->
                        <% @artist.musicians.each do |musician| %>
                        <div class="member">
                            <span><%= link_to musician.name, musician_path(musician.id), :class => "member__name color-darkest-grey" %></span> &mdash; <span class="member__instrument"><%= musician.instrument %></span>
                        </div>
                        <% end %>
                      
                    </div>
                </div>

                <div class="line margin-top">
                </div>

                <div class="artistInfoWrapper flex">
                    <div class="artistInfoTitle">
                        ALBUMS
                    </div>

                <div class="sortText color-light-grey">
                    SORT
                </div>

                <div class="sortBy">
                     <select>
                            <option>UPLOAD DATE, NEW TO OLD</option>
                            <option>Option 2</option>
                            <option>Option 3</option>
                        </select>

                        <div class="arrows">
                            <i class="arr-up"></i>
                            <i class="arr-down"></i>
                        </div>
                </div>
                </div>

                <div class="line">
                </div>
                
                <div class="margin-top flex populateAlbums">
                    <% @albums.each do |album| %>
                    <div class="album">

                        <div class="album__albumName color-dark-grey">
                            <%= album.name %>
                        </div>

                        <div class="album__artistName color-dark-grey">
                            <%= @artist.name %>
                        </div>
                    </div>
                        <% end %>
                    </div>

            </div>

             <div class="filterOptions  flex margin-sm margin-right-big">
                <div class="filterTitle">
                    <div class="filterTitle__text">
                        CITIES
                    </div>
                </div>
                <div class="filterWrapper">
                    <% @array_of_cities.each do |city| %>
                    <div>
                      <%= link_to "#{city} (#{@hash_of_city_albums_count[city]})", root_path(:city => city), :class => "filterText color-mid-grey" %>
                    </div>
                  <% end %>
                    
                </div>

                <div class="filterTitle">
                    <div class="filterTitle__text">
                        GENRES
                    </div>
                </div>
                <div class="filterWrapper">
                    <% @genres.each do |name, count| %>
                    <div>
                        <%= link_to "#{name} (#{count})", root_path(:genre => name), :class => "filterText color-mid-grey" %>
                    </div>
                    <% end %>
                </div>

                <div class="filterTitle">
                    <div class="filterTitle__text">
                        DECADES
                    </div>
                </div>
                <div class="filterWrapper">
                    <div class="filterText color-mid-grey">
                        Text
                        <!-- List of decades will need to be dynamically populated -->
                    </div>
                </div>

                <div class="filterTitle">
                    <div class="filterTitle__text">
                        FORMAT
                    </div>
                </div>
                <div class="filterWrapper">
                    <% @format.each do |name, count| %>
                    <div>
                        <%= link_to "#{name} (#{count})", root_path(format: name), :class => "filterText color-mid-grey" %>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>

    </div>