config/routes.rb
Rails.application.routes.draw do

  resources :photos
  namespace :admin do
    resources :users
    resources :albums
    resources :artists
    resources :musicians
    resources :songs

    root to: "users#index"
  end

  resources :api, :only => :index

  resources :songs

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/index'
  delete 'users/sign_out'

  resources :artists
  resources :albums
  resources :search
  resources :musicians

  root 'home#index'

  resources :user

end

app/models/musician.rb
class Musician < ActiveRecord::Base
	belongs_to :artist
end

app/controllers/admin/musicians_controller.rb
module Admin
  class MusiciansController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Musician.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Musician.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/musicians_controller.rb
class MusiciansController < ApplicationController
	def index
		@musicians = Musician.all.page(params[:page]).per(3)
	end

	def show
		@musician = Musician.find(params[:id])
		@albums = Album.where(:artist_id => @musician.artist.id)
		@img = Artist.find(@musician.artist_id).url

		@array_of_cities = Album.list_of_locations

		@hash_of_city_albums_count = Album.count_of_albums_per_city

		@genres = Album.album_count(Album.uniq.pluck(:genre))
		@format = Album.album_count(Album.uniq.pluck(:format))
		@artist = Artist.find(params[:id])
	end
	
		# @genre_album_count = Album.count_of_albums_per_genre

	
end

app/views/musicians/index.html.erb
<h1>All Musicians</h1>

<table>

	<thead>
		<tr>
			<th>Name</th>
		</tr>
	</thead>

	<tbody>
		<% @musicians.each do |musician| %>
			<tr id="musician_<%= musician.id %>">
				<td><%= musician.name %></td>
				<td><%= link_to "Details", musician_path(musician.id) %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= paginate @musicians %>

app/views/musicians/show.html.erb
<div class="bodyContainer">

        <div class="rowWrapper flex margin-top margin-left margin-right-big"">
            <div class="searchBox search flex">
                    <form action="">
                        <input method="" name="" type="text" placeholder="Search for an album, artist or track..." class="search__input padding-10" id="search" required><span class="icons icons--search color-light-grey"></span>
                    </form>
            </div>

            <span class="share">
                <span class="share__text font-oswald color-mid-grey">SHARE THIS MUSICIAN</span>
                <span class="icons icons--twitter color-dark-grey"></span>
                <span class="icons icons--fb color-dark-grey"></span>
            </span>
        </div>


        <div class="contentContainer flex">
            <div class="leftContainer flex margin-top margin-left margin-btm">

                <div class="pageTitle">

                    <div class="pageTitle__text color-white flex space-between">
                        <div>
                            <%= @musician.name %>
                            <span class="filterType"> | Musician</span>
                        </div>
                        <span><%= link_to "EDIT MUSICIAN", edit_admin_musician_path(@musician.id), :class => "editLink" %></span>

                    </div>
                </div>

                <div class="artistImgContainer">
                	<%= image_tag "#{@img}" %>
                </div>
                
                <div class="line margin-top">
                </div>

                <div class="artistInfoWrapper flex">
                    <div class="artistInfoTitle">
                        ALBUMS
                    </div>

                    <div class="sort flex">
                        <div class="sortText color-light-grey">
                            SORT
                        </div>

                        <div class="sortBy">
                             <select>
                                <option>UPLOAD DATE, NEW TO OLD</option>
                                <option>Option 2</option>
                                <option>Option 3</option>
                            </select>

                            <div class="arrows">
                                <i class="arr-up"></i>
                                <i class="arr-down"></i>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="line">
                </div>
                
                <div class="margin-top flex populateAlbums">
                    <% @albums.each do |album| %>
                    <div class="album">                        
                        <div class="album__albumName color-dark-grey">
                            <%= album.name %>
                        </div>

                        <div class="album__artistName color-dark-grey">
                            <%= Artist.find(album.artist_id).name %>
                        </div>
                    </div>
                        <% end %>
                    </div>

            </div>

             <div class="filterOptions flex margin-sm margin-right-big">
                <div class="filterTitle">
                    <div class="filterTitle__text">
                        CITIES
                    </div>
                </div>
                <div class="filterWrapper">
                    <% @array_of_cities.each do |city| %>
                    <div>
                      <%= link_to "#{city} (#{@hash_of_city_albums_count[city]})", root_path(:city => city), :class => "filterText color-mid-grey" %>
                    </div>
                  <% end %>
                    
                </div>

                <div class="filterTitle">
                    <div class="filterTitle__text">
                        GENRES
                    </div>
                </div>
                <div class="filterWrapper">
                    <% @genres.each do |name, count| %>
                    <div>
                        <%= link_to "#{name} (#{count})", root_path(:genre => name), :class => "filterText color-mid-grey" %>
                    </div>
                    <% end %>
                </div>

                <div class="filterTitle">
                    <div class="filterTitle__text">
                        DECADES
                    </div>
                </div>
                <div class="filterWrapper">
                    <div class="filterText color-mid-grey">
                        Text
                        <!-- List of decades will need to be dynamically populated -->
                    </div>
                </div>

                <div class="filterTitle">
                    <div class="filterTitle__text">
                        FORMAT
                    </div>
                </div>
                <div class="filterWrapper">
                    <% @format.each do |name, count| %>
                    <div>
                        <%= link_to "#{name} (#{count})", root_path(format: name), :class => "filterText color-mid-grey" %>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>

    </div>